version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    container_name: db_container
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app_network

  # Python Flask Backend Service
  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network
    tty: true
    stdin_open: true
    command: /bin/bash

  # Frontend Service (React/Vue/Angular)
  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app_network
    # depends_on:
    #   - backend

networks:
  app_network:
    driver: bridge

volumes:
  db_volume:
    driver: local